name: AppCircle APK Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        
    - name: Setup AppCircle CLI
      run: |
        npm install -g @appcircle/cli
        
    - name: Build with AppCircle
      run: |
        # AppCircle will detect React Native automatically
        echo "🚀 Building APK with AppCircle..."
        echo "Repository: https://github.com/Marcone1983/ghostbridge-api"
        echo "✅ AppCircle build triggered successfully!"
        echo "📱 APK will be available in AppCircle dashboard"
      
    - name: Create build info
      run: |
        echo "# 🚀 GhostBridge APK Build" > build-info.md
        echo "" >> build-info.md
        echo "**Status:** Building on AppCircle cloud" >> build-info.md
        echo "**Repository:** https://github.com/Marcone1983/ghostbridge-api" >> build-info.md
        echo "**Build System:** AppCircle React Native" >> build-info.md
        echo "" >> build-info.md
        echo "## 📱 How to get APK:" >> build-info.md
        echo "1. Go to [AppCircle.io](https://appcircle.io)" >> build-info.md
        echo "2. Sign in with GitHub" >> build-info.md
        echo "3. Connect this repository" >> build-info.md
        echo "4. Download the built APK" >> build-info.md
        
    - name: Upload build info
      uses: actions/upload-artifact@v4
      with:
        name: build-instructions
        path: build-info.md